# packages : issues/ vulnerabilities (scan)
# pip audit (for python)

name: Dependencies scan

on:
    workflow_call:
      
jobs:
  dependencies-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Pip Audit
        run: pip install pip-audit

      - name: audit dependencies
        run: pip-audit -r requirements.txt