
name: DevSecOps pipeline

on: 
    workflow_dispatch:
      
jobs:  # Continous Integration with Security Scanning (CI)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit

    dependencies-scan:
        uses: ./.github/workflows/dependencies-scan.yml

    docker-lint-scan:
        uses: ./.github/workflows/docker-lint.yml


    # Docker build and push (CD)
    docker-build:
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit
        needs: [code-quality, secrets-scan, dependencies-scan, docker-lint-scan]


    # Image scan
    image-scan:
        uses: ./.github/workflows/image-scan.yml
        needs: [docker-build]
        secrets: inherit

    # Deploy app to production
    deploy-to-server:
        uses: ./.github/workflows/deploy-to-server.yml
        needs: [image-scan]
        secrets: inherit
