# API keys, sensetive data, credentials
# Gitleaks

name: secrets scan

on: 
    workflow_call:
      
jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0               # checks code from 1st commit

      - name: Run Gitleaks Scanner
        uses: gitleaks/gitleaks-action@v2
        env:
            GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}   # github manages itself
            GITLEAKS_LICENCE: ${{ secrets.GITLEAKS_LICENCE }}
